### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by eliabieri** [nekromant/pl2303gpio#2]
Is there a way to use this on a mac?
I can compile it with 2 errors but then the installation process fails because of:
cp pl2303gpio /usr/local/bin
cp cp2103gpio /usr/local/bin
cp 10-pl2303userspace.rules /etc/udev/rules.d
cp: /etc/udev/rules.d: No such file or directory
make: *** [install] Error 1

**Comment by nekromant** [comment]
I have no mac to test it on, unfortunately. 
You have no udev on mac, so no /etc/udev/ dir, so the error makes sense. Apart from udev stuff you don't need, everything looks installed, so you may safely ignore it and try running the actual binaries and see if they work for you.

**Comment by eliabieri** [comment]
Oh wow it works!
I installed gcc and pkg-config with homebrew. Im on osx 10.10.3 yosemite.
You can update the READE and note that mac users can ignore the errors.
Thanks for your help!
