### ISSUE TITLE
About HXD

### ISSUE THREAD

**Issue by wild0** [nekromant/pl2303gpio#4]
Will this repo support pl2303 HxD? I can control GPIO0 and GPIO1 in Pl2303 HXD from this repo
. But I don't know how to set GPIO2 and GPIO3 in HXD. Or can u give me some advise?

Thanks

**Comment by ticchen** [comment]
> Will this repo support pl2303 HxD? I can control GPIO0 and GPIO1 in Pl2303 HXD from this repo
> . But I don't know how to set GPIO2 and GPIO3 in HXD. Or can u give me some advise?
> 
> Thanks

Could you have a try with my changes? 
https://github.com/ticchen/pl2303gpio

**Comment by nekromant** [comment]
> > Will this repo support pl2303 HxD? I can control GPIO0 and GPIO1 in Pl2303 HXD from this repo
> > . But I don't know how to set GPIO2 and GPIO3 in HXD. Or can u give me some advise?
> > Thanks
> 
> Could you have a try with my changes?
> https://github.com/ticchen/pl2303gpio
> Thanks.

Thanks a lot for the merge request, I've merged it into master.
