### ISSUE TITLE
undefined reference to `libusb_get_port_number'

### ISSUE THREAD

**Issue by dony71** [nekromant/pl2303gpio#5]
I try to cross compile this for asus merlin router
https://github.com/RMerl/asuswrt-merlin.ng

Compile gives error below
/opt/brcm-arm/bin/arm-linux-gcc -I/usr/include/libusb-1.0 -Wall -Werror -I"../include" -o pl2303gpio usb.c main.c pl2303.o -lusb-1.0
/tmp/ccWQmRhn.o: In function `ncusb_device_list':
usb.c:(.text+0x1a4): undefined reference to `libusb_get_port_number'
/tmp/ccWQmRhn.o: In function `ncusb_find_and_open':
usb.c:(.text+0x310): undefined reference to `libusb_get_port_number'
collect2: ld returned 1 exit status
Makefile:14: recipe for target 'pl2303gpio' failed
make: *** [pl2303gpio] Error 1

Then I google, found this
https://github.com/rockchip-linux/rkdeveloptool/issues/30
so I try to change libusb_get_port_number(device) to libusb_get_device_address(device) in usb.c

Compile success after modification, however execute binary give segmentation fault
Any fix for this?

nb : libusb-1.0 source code for asus merlin below
https://github.com/RMerl/asuswrt-merlin.ng/tree/master/release/src/router/libusb10

**Comment by nekromant** [comment]
Hi there! 
These are two totally different calls they are doing totally different stuff. 
You may try adding
```c
#define libusb_get_port_number(x) (0)
```
as a workaround. Multiple pl2303 devices handling will not work, but the rest most likely will. 
It looks like the problem of libusb version on your hardware, so I'm closing the issue.
